server:
  port: 8081
  ssl:
    enabled: true
    key-store: src/main/resources/client.jks
    key-store-password: 123456
    key-alias: client
    protocol: TLS
spring:
  application:
    name: client


eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
    enabled: true
  instance:
      statusPageUrlPath: https://localhost:8761/info
      healthCheckUrlPath: https://localhost:8761/health
      leaseRenewalIntervalInSeconds: 10
      securePort: ${server.port}
      securePortEnabled: true
      nonSecurePortEnabled: false

