server:
  port: 8081
  ssl:
    enabled: true
    key-store: src/main/resources/client.jks
    key-store-password: 123456
    key-alias: client
    protocol: TLS
    ciphers: SSL_RSA_WITH_RC4_128_MD5, SSL_RSA_WITH_RC4_128_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_DES_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA, SSL_DHE_DSS_WITH_DES_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
spring:
  application:
    name: client


eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
    enabled: true
  instance:
      statusPageUrlPath: https://localhost:8761/info
      healthCheckUrlPath: https://localhost:8761/health
      leaseRenewalIntervalInSeconds: 10
      securePort: ${server.port}
      securePortEnabled: true
      nonSecurePortEnabled: false

