server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:discoveryService.p12
    key-store-password: drytcgvhbjk
    trust-store: classpath:discoveryService.p12
    trust-store-password: drytcgvhbjk
    key-alias: discoveryService
    client-auth: need
    protocol: TLS

spring:
  application:
    name:  discovery

eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    nonSecurePortEnabled: false
    securePortEnabled: true
    secureVirtualHostName: ${spring.application.name}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
    metadataMap:
      hostname: ${eureka.instance.hostname}
      securePort: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/

